### ISSUE TITLE
提一些意见

### ISSUE THREAD

**Issue by RyensX** [MaybeQHL/my_danmu_pub#2]
我发现你的集弹幕数据其实是根据number来单独存储的，其实我推荐做一个算法来匹配集数，比如第一集和第1及以及1集、1其实都是同一集，这样不同渠道就可以共享弹幕的了

**Comment by MaybeQHL** [comment]
我后面的算法是这个样。 第01集  1集  01都是同一集 ，至于中文的确实没有适配, 但是通过观察三方平台中间大部分都是通过数字来解决的。
![image](https://user-images.githubusercontent.com/34638673/183410557-4668b371-84d1-49c1-9ba6-322d4b008a7f.png)

**Comment by MaybeQHL** [comment]
中文的话如果发现有平台是中文我在做一下处理。

**Comment by RyensX** [comment]
还有一个地方，我发现你虽然做了B站弹幕适配但却是独立的，如果能合并到现有接口共享并且数据统一就好了

**Comment by MaybeQHL** [comment]
B站弹幕和我的弹幕也是会合并的 只不过我的弹幕太少了。而且目前一次只取6000条。

**Comment by RyensX** [comment]
> B站弹幕和我的弹幕也是会合并的 只不过我的弹幕太少了。而且目前一次只取6000条。

OK，感谢开发者

**Comment by MaybeQHL** [comment]
目前就是没有对接腾讯视频 API，还没找到合适的方式。如果有思路和方法可以@我

**Comment by MaybeQHL** [comment]
> > B站弹幕和我的弹幕也是会合并的 只不过我的弹幕太少了。而且目前一次只取6000条。
> 
> OK，感谢开发者

没事，利人利己，我顺便也学习一下nodejs 哈哈

**Comment by MaybeQHL** [comment]
有没有人提供一下稳定的国内IP代理，bilibili国外的服务器查不出来。

**Comment by MaybeQHL** [comment]
> 有没有人提供一下稳定的国内IP代理，bilibili番剧接口国外的服务器查不出来。

**Comment by RyensX** [comment]
> 有没有人提供一下稳定的国内IP代理，bilibili番剧接口国外的服务器查不出来。

抱歉，暂时没有闲置的。
不过我试了一下弹幕接口国外IP是可以直接请求的，至于需要的番剧剧集id，其实可以直接都爬下来，还省了一次请求

**Comment by MaybeQHL** [comment]
有的查的出来 有的查不出来 奇怪，算了不管了。番剧的信息我都会缓存的。只要查过一次之后都挺快。
