### ISSUE TITLE
想问一下服务已经不维护了吗

### ISSUE THREAD

**Issue by RyensX** [MaybeQHL/my_danmu_pub#4]
502了

**Comment by MaybeQHL** [comment]
不知道为啥关闭了，已经重启了。

**Comment by MaybeQHL** [comment]
今天对查询速度进行了几何倍数的优化，可以测试一下查询速度是不是快很多。

**Comment by MaybeQHL** [comment]
大概5秒内就可以查询出来。

**Comment by MaybeQHL** [comment]
然后就是最近准备开发v4版本的查询 因为v3版本有好多冗余的query查询字段以及返回的字段可以尽可能的把字节缩小。

**Comment by RyensX** [comment]
好像确实快了点。V4到时候我再试试看接入

**Comment by MaybeQHL** [comment]
@RyensX  https://console-docs.apipost.cn/preview/508e9181d81a978c/d92a27922cea066a?target_id=681ffe0e-6e16-4f5b-a913-41f8c6e9c2ec v4测试版有什么建议的吗

**Comment by RyensX** [comment]
> @RyensX https://console-docs.apipost.cn/preview/508e9181d81a978c/d92a27922cea066a?target_id=681ffe0e-6e16-4f5b-a913-41f8c6e9c2ec v4测试版有什么建议的吗

就是相比V3自定义少了然后内部做了优化？之前的弹弹重复以及弹幕分布问题有处理吗

**Comment by MaybeQHL** [comment]
弹幕分部是指的是弹幕数据均匀分布吗？  我现在新写的算法是每30秒内弹幕不超过200多条。至于 弹幕重复 （如果是二个用户发的同一个弹幕那么去重复是不是有违这个逻辑）。 目前用这种算法后30秒内不会有太多的弹幕，重复的也不会太夸张，应该体验还可以。

**Comment by MaybeQHL** [comment]
不管视频的时间是多长 反正以 time/30*200 =弹幕总数

**Comment by RyensX** [comment]
好吧，到时候试试
